version: "3"
services:
  jenkins:
    build: .
    image: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - D:\\dev\\jenkins-container\\data:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    privileged: true

