apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{ .Values.namespace }}
  labels:
    app: jenkins
    service: jenkins-service
spec:
  ports:
    - port: 8080
      name: interface
      targetPort: 8080
    - port: 50000
      name: data
      targetPort: 50000
  selector:
    app: jenkins
    service: jenkins
